<?xml version="1.0"?>
<robot name="$(arg robot_name)" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Peavy - This file was generated mostly by hand as a copy from the
       nuclear_facility.xacro file in order to simulate a couple of long
       hallways with many doors-->

  
  <!-- Parameters -->
  <xacro:property name="wall_height" value="3.5" />
  <xacro:property name="wall_thickness" value="0.20" />
  <xacro:property name="door_width" value="1.00" />
  <xacro:property name="door_space" value="1.00" />
  <xacro:property name="hall_width" value="3.00" />
  <xacro:property name="core_width" value="11.00" />
  <xacro:property name="building_width" value="23.00" />
  <xacro:property name="floor_width" value="25.00" />
  <xacro:property name="floor_thickness" value="0.001" />


  <!-- The main footprint link for this robotic building -->
  <link name="building_footprint_link" />


  <!-- ==================  -->
  <!--   building_base -->
  <joint name="building_base_joint" type="fixed">
    <parent link="building_footprint_link" />
    <origin xyz="0 0 0" rpy="0 0 0" />
    <child link="building_base_link" />
  </joint>
  <link name="building_base_link">
    <inertial>
      <mass value="10000" />
      <com xyz="0 0 0" />
      <inertia ixx="10000" ixy="0"     ixz="0"
                           iyy="10000" iyz="0"
                                       izz="10000" />
    </inertial> 
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry name="building_base_visual_geom">
        <box size="0.001 0.001 0.001" />
      </geometry>
    </visual> 
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry name="building_base_collision_geom">
        <box size="0.001 0.001 0.001" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="building_base_link">
    <material>PR2/Grey</material>
    <mu1>50.0</mu1>
    <mu2>50.0</mu2>
    <kp>1000000000.0</kp>
    <kd>1.0</kd>
  </gazebo>

  <!-- ==================  -->
  <!--   floor_001 -->
  <joint name="floor_001_joint" type="fixed">
    <parent link="building_base_link" />
    <origin xyz="0  0  0" rpy="0 0 0" />
    <child link="floor_001_link" />
  </joint>
  <link name="floor_001_link">
    <inertial>
      <mass value="10000" />
      <com xyz="0 0 0" />
      <inertia ixx="10" ixy="0"  ixz="0"
                        iyy="10" iyz="0"
                                 izz="10" />
    </inertial> 
    <visual>
      <origin xyz="${-1.0 + floor_width / 2}  ${-1.0 + floor_width / 2}  0.0" rpy="0 0 0" />
      <geometry name="floor_001_visual_geom">
        <box size="${floor_width} ${floor_width} ${floor_thickness}" />
      </geometry>
    </visual> 
    <collision>
      <origin xyz="${-1.0 + floor_width / 2}  ${-1.0 + floor_width / 2}  ${-2 * floor_thickness}" rpy="0 0 0" />
      <geometry name="floor_001_collision_geom">
        <box size="${floor_width} ${floor_width} ${floor_thickness}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="floor_001_link">
    <material>PR2/Grey</material>
    <mu1>50.0</mu1>
    <mu2>50.0</mu2>
    <kp>1000000000.0</kp>
    <kd>1.0</kd>
  </gazebo>

  
  <!-- ===================  -->
  <!--   hallway_001 -->
  
  <joint name="hallway_001__wall_001_joint" type="fixed" >
    <parent link="floor_001_link" />
    <origin xyz="0  ${(2 * hall_width + 3 * door_space) / 2}  0" rpy="0  0  1.5708" />
    <child link="hallway_001__wall_001" />
  </joint>
  <link name="hallway_001__wall_001">
    <inertial>
      <mass value="0"/>
      <origin rpy="0  0  0" xyz="0  0  0"/>
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
    </inertial>
    <collision name="hallway_001__wall_001_Collision">
      <origin rpy="0  0  0" xyz="0  ${wall_thickness/2}  ${wall_height / 2}"/>
      <geometry>
        <box size="${2 * hall_width + 3 * door_space} ${wall_thickness} ${wall_height}"/>
      </geometry>
    </collision>
    <visual name="hallway_001__wall_001_Visual">
      <origin rpy="0  0  0" xyz="0  ${wall_thickness/2}  ${wall_height / 2}"/>
      <geometry>
        <box size="${2 * hall_width + 3 * door_space} ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>
  </link>  
  <gazebo reference="hallway_001__wall_001">
    <material>PR2/Grey2</material>
    <laserRetro>1000</laserRetro>
    <selfCollide>false</selfCollide>
  </gazebo>
  
  <joint name="hallway_001__wall_002_joint" type="fixed" >
    <parent link="floor_001_link" />
    <origin xyz="0  ${2 * hall_width + 3.5 * door_space +  door_width}  0" rpy="0  0  1.5708" />
    <child link="hallway_001__wall_002" />
  </joint>
  <link name="hallway_001__wall_002">
    <inertial>
      <mass value="0"/>
      <origin rpy="0  0  0" xyz="0  0  0"/>
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
    </inertial>
    <collision name="hallway_001__wall_002_Collision">
      <origin rpy="0  0  0" xyz="0  ${wall_thickness/2}  ${wall_height / 2}"/>
      <geometry>
        <box size="${door_space} ${wall_thickness} ${wall_height}"/>
      </geometry>
    </collision>
    <visual name="hallway_001__wall_002_Visual">
      <origin rpy="0  0  0" xyz="0  ${wall_thickness/2}  ${wall_height / 2}"/>
      <geometry>
        <box size="${door_space} ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>
  </link>  
  <gazebo reference="hallway_001__wall_002">
    <material>PR2/Grey2</material>
    <laserRetro>1000</laserRetro>
    <selfCollide>false</selfCollide>
  </gazebo>
  
  <joint name="hallway_001__wall_003_joint" type="fixed" >
    <parent link="floor_001_link" />
    <origin xyz="0  ${2 * hall_width + 4.5 * door_space +  2 * door_width}  0" rpy="0  0  1.5708" />
    <child link="hallway_001__wall_003" />
  </joint>
  <link name="hallway_001__wall_003">
    <inertial>
      <mass value="0"/>
      <origin rpy="0  0  0" xyz="0  0  0"/>
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
    </inertial>
    <collision name="hallway_001__wall_003_Collision">
      <origin rpy="0  0  0" xyz="0  ${wall_thickness/2}  ${wall_height / 2}"/>
      <geometry>
        <box size="${door_space} ${wall_thickness} ${wall_height}"/>
      </geometry>
    </collision>
    <visual name="hallway_001__wall_003_Visual">
      <origin rpy="0  0  0" xyz="0  ${wall_thickness/2}  ${wall_height / 2}"/>
      <geometry>
        <box size="${door_space} ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>
  </link>  
  <gazebo reference="hallway_001__wall_003">
    <material>PR2/Grey2</material>
    <laserRetro>1000</laserRetro>
    <selfCollide>false</selfCollide>
  </gazebo>
  
  <joint name="hallway_001__wall_004_joint" type="fixed" >
    <parent link="floor_001_link" />
    <origin xyz="0  ${2 * hall_width + 5 * door_space +  3 * door_width + (2 * hall_width + 3 * door_space) / 2}  0" rpy="0  0  1.5708" />
    <child link="hallway_001__wall_004" />
  </joint>
  <link name="hallway_001__wall_004">
    <inertial>
      <mass value="0"/>
      <origin rpy="0  0  0" xyz="0  0  0"/>
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
    </inertial>
    <collision name="hallway_001__wall_004_Collision">
      <origin rpy="0  0  0" xyz="0  ${wall_thickness/2}  ${wall_height / 2}"/>
      <geometry>
        <box size="${2 * hall_width + 3 * door_space} ${wall_thickness} ${wall_height}"/>
      </geometry>
    </collision>
    <visual name="hallway_001__wall_004_Visual">
      <origin rpy="0  0  0" xyz="0  ${wall_thickness/2}  ${wall_height / 2}"/>
      <geometry>
        <box size="${2 * hall_width + 3 * door_space} ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>
  </link>  
  <gazebo reference="hallway_001__wall_004">
    <material>PR2/Grey2</material>
    <laserRetro>1000</laserRetro>
    <selfCollide>false</selfCollide>
  </gazebo>

  
  <!-- ===================  -->
  <!--   hallway_002 -->
  
  <joint name="hallway_002__wall_001_joint" type="fixed" >
    <parent link="floor_001_link" />
    <origin xyz="${building_width / 2}  0  0" rpy="0  0  0" />
    <child link="hallway_002__wall_001" />
  </joint>
  <link name="hallway_002__wall_001">
    <inertial>
      <mass value="0"/>
      <origin rpy="0  0  0" xyz="0  0  0"/>
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
    </inertial>
    <collision name="hallway_002__wall_001_Collision">
      <origin rpy="0  0  0" xyz="0   0  ${wall_height / 2}"/>
      <geometry>
        <box size="${building_width}  ${wall_thickness}  ${wall_height}"/>
      </geometry>
    </collision>
    <visual name="hallway_002__wall_001_Visual">
      <origin rpy="0  0  0" xyz="0  0  ${wall_height / 2}"/>
      <geometry>
        <box size="${building_width}  ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>
  </link>  
  <gazebo reference="hallway_002__wall_001">
    <material>PR2/Grey2</material>
    <laserRetro>1000</laserRetro>
    <selfCollide>false</selfCollide>
  </gazebo>
  
  <!-- ===================  -->
  <!--   hallway_003 -->
  
  <joint name="hallway_003__wall_001_joint" type="fixed" >
    <parent link="floor_001_link" />
    <origin xyz="${building_width}  ${building_width / 2}  0" rpy="0  0  1.5708" />
    <child link="hallway_003__wall_001" />
  </joint>
  <link name="hallway_003__wall_001">
    <inertial>
      <mass value="0"/>
      <origin rpy="0  0  0" xyz="0  0  0"/>
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
    </inertial>
    <collision name="hallway_003__wall_001_Collision">
      <origin rpy="0  0  0" xyz="0   0  ${wall_height / 2}"/>
      <geometry>
        <box size="${building_width}  ${wall_thickness}  ${wall_height}"/>
      </geometry>
    </collision>
    <visual name="hallway_003__wall_001_Visual">
      <origin rpy="0  0  0" xyz="0  0  ${wall_height / 2}"/>
      <geometry>
        <box size="${building_width}  ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>
  </link>  
  <gazebo reference="hallway_003__wall_001">
    <material>PR2/Grey2</material>
    <laserRetro>1000</laserRetro>
    <selfCollide>false</selfCollide>
  </gazebo>
  
  <!-- ===================  -->
  <!--   hallway_004 -->
  
  <joint name="hallway_004__wall_001_joint" type="fixed" >
    <parent link="floor_001_link" />
    <origin xyz="${building_width / 2}  ${building_width}  0" rpy="0  0  0" />
    <child link="hallway_004__wall_001" />
  </joint>
  <link name="hallway_004__wall_001">
    <inertial>
      <mass value="0"/>
      <origin rpy="0  0  0" xyz="0  0  0"/>
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
    </inertial>
    <collision name="hallway_004__wall_001_Collision">
      <origin rpy="0  0  0" xyz="0   0  ${wall_height / 2}"/>
      <geometry>
        <box size="${building_width}  ${wall_thickness}  ${wall_height}"/>
      </geometry>
    </collision>
    <visual name="hallway_004__wall_001_Visual">
      <origin rpy="0  0  0" xyz="0  0  ${wall_height / 2}"/>
      <geometry>
        <box size="${building_width}  ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>
  </link>  
  <gazebo reference="hallway_004__wall_001">
    <material>PR2/Grey2</material>
    <laserRetro>1000</laserRetro>
    <selfCollide>false</selfCollide>
  </gazebo>

    
  <!-- ===================  -->
  <!--     core_001         -->
  
  <joint name="core_001__wall_001_joint" type="fixed" >
    <parent link="floor_001_link" />
    <origin xyz="${2 * hall_width}  ${2 * hall_width + 3 * door_space / 2}  0" rpy="0  0  1.5708" />
    <child link="core_001__wall_001" />
  </joint>
  <link name="core_001__wall_001">
    <inertial>
      <mass value="0"/>
      <origin rpy="0  0  0" xyz="0  0  0"/>
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
    </inertial>
    <collision name="core_001__wall_001_Collision">
      <origin rpy="0  0  0" xyz="0   0  ${wall_height / 2}"/>
      <geometry>
        <box size="${3 * door_space}  ${wall_thickness}  ${wall_height}"/>
      </geometry>
    </collision>
    <visual name="core_001__wall_001_Visual">
      <origin rpy="0  0  0" xyz="0  0  ${wall_height / 2}"/>
      <geometry>
        <box size="${3 * door_space}  ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>
  </link>  
  <gazebo reference="core_001__wall_001">
    <material>PR2/Grey2</material>
    <laserRetro>1000</laserRetro>
    <selfCollide>false</selfCollide>
  </gazebo>
  
  <joint name="core_001__wall_002_joint" type="fixed" >
    <parent link="floor_001_link" />
    <origin xyz="${2 * hall_width}  ${2 * hall_width + 3.5 * door_space + door_width}  0" rpy="0  0  1.5708" />
    <child link="core_001__wall_002" />
  </joint>
  <link name="core_001__wall_002">
    <inertial>
      <mass value="0"/>
      <origin rpy="0  0  0" xyz="0  0  0"/>
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
    </inertial>
    <collision name="core_001__wall_002_Collision">
      <origin rpy="0  0  0" xyz="0   0  ${wall_height / 2}"/>
      <geometry>
        <box size="${door_space}  ${wall_thickness}  ${wall_height}"/>
      </geometry>
    </collision>
    <visual name="core_001__wall_002_Visual">
      <origin rpy="0  0  0" xyz="0  0  ${wall_height / 2}"/>
      <geometry>
        <box size="${door_space}  ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>
  </link>  
  <gazebo reference="core_001__wall_002">
    <material>PR2/Grey2</material>
    <laserRetro>1000</laserRetro>
    <selfCollide>false</selfCollide>
  </gazebo>
  
  <joint name="core_001__wall_003_joint" type="fixed" >
    <parent link="floor_001_link" />
    <origin xyz="${2 * hall_width}  ${2 * hall_width + 4.5 * door_space + 2 * door_width}  0" rpy="0  0  1.5708" />
    <child link="core_001__wall_003" />
  </joint>
  <link name="core_001__wall_003">
    <inertial>
      <mass value="0"/>
      <origin rpy="0  0  0" xyz="0  0  0"/>
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
    </inertial>
    <collision name="core_001__wall_003_Collision">
      <origin rpy="0  0  0" xyz="0   0  ${wall_height / 2}"/>
      <geometry>
        <box size="${door_space}  ${wall_thickness}  ${wall_height}"/>
      </geometry>
    </collision>
    <visual name="core_001__wall_003_Visual">
      <origin rpy="0  0  0" xyz="0  0  ${wall_height / 2}"/>
      <geometry>
        <box size="${door_space}  ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>
  </link>  
  <gazebo reference="core_001__wall_003">
    <material>PR2/Grey2</material>
    <laserRetro>1000</laserRetro>
    <selfCollide>false</selfCollide>
  </gazebo>
  
  <joint name="core_001__wall_004_joint" type="fixed" >
    <parent link="floor_001_link" />
    <origin xyz="${2 * hall_width}  ${2 * hall_width + 6.5 * door_space + 3 * door_width}  0" rpy="0  0  1.5708" />
    <child link="core_001__wall_004" />
  </joint>
  <link name="core_001__wall_004">
    <inertial>
      <mass value="0"/>
      <origin rpy="0  0  0" xyz="0  0  0"/>
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
    </inertial>
    <collision name="core_001__wall_004_Collision">
      <origin rpy="0  0  0" xyz="0   0  ${wall_height / 2}"/>
      <geometry>
        <box size="${3 * door_space}  ${wall_thickness}  ${wall_height}"/>
      </geometry>
    </collision>
    <visual name="core_001__wall_004_Visual">
      <origin rpy="0  0  0" xyz="0  0  ${wall_height / 2}"/>
      <geometry>
        <box size="${3 * door_space}  ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>
  </link>  
  <gazebo reference="core_001__wall_004">
    <material>PR2/Grey2</material>
    <laserRetro>1000</laserRetro>
    <selfCollide>false</selfCollide>
  </gazebo>
    
  <!-- ===================  -->
  <!--     core_002         -->
  
  <joint name="core_002__wall_001_joint" type="fixed" >
    <parent link="floor_001_link" />
    <origin xyz="${2 * hall_width + core_width / 2} ${2 * hall_width}   0" rpy="0  0  0" />
    <child link="core_002__wall_001" />
  </joint>
  <link name="core_002__wall_001">
    <inertial>
      <mass value="0"/>
      <origin rpy="0  0  0" xyz="0  0  0"/>
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
    </inertial>
    <collision name="core_002__wall_001_Collision">
      <origin rpy="0  0  0" xyz="0   0  ${wall_height / 2}"/>
      <geometry>
        <box size="${core_width}  ${wall_thickness}  ${wall_height}"/>
      </geometry>
    </collision>
    <visual name="core_002__wall_001_Visual">
      <origin rpy="0  0  0" xyz="0  0  ${wall_height / 2}"/>
      <geometry>
        <box size="${core_width}  ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>
  </link>  
  <gazebo reference="core_002__wall_001">
    <material>PR2/Grey2</material>
    <laserRetro>1000</laserRetro>
    <selfCollide>false</selfCollide>
  </gazebo>
    
  <!-- ===================  -->
  <!--     core_003         -->
  
  <joint name="core_003__wall_001_joint" type="fixed" >
    <parent link="floor_001_link" />
    <origin xyz="${2 * hall_width + core_width}  ${2 * hall_width + 3 * door_space / 2}  0" rpy="0  0  1.5708" />
    <child link="core_003__wall_001" />
  </joint>
  <link name="core_003__wall_001">
    <inertial>
      <mass value="0"/>
      <origin rpy="0  0  0" xyz="0  0  0"/>
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
    </inertial>
    <collision name="core_003__wall_001_Collision">
      <origin rpy="0  0  0" xyz="0   0  ${wall_height / 2}"/>
      <geometry>
        <box size="${3 * door_space}  ${wall_thickness}  ${wall_height}"/>
      </geometry>
    </collision>
    <visual name="core_003__wall_001_Visual">
      <origin rpy="0  0  0" xyz="0  0  ${wall_height / 2}"/>
      <geometry>
        <box size="${3 * door_space}  ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>
  </link>  
  <gazebo reference="core_003__wall_001">
    <material>PR2/Grey2</material>
    <laserRetro>1000</laserRetro>
    <selfCollide>false</selfCollide>
  </gazebo>
  
  <joint name="core_003__wall_002_joint" type="fixed" >
    <parent link="floor_001_link" />
    <origin xyz="${2 * hall_width + core_width}  ${2 * hall_width + 3.5 * door_space + door_width}  0" rpy="0  0  1.5708" />
    <child link="core_003__wall_002" />
  </joint>
  <link name="core_003__wall_002">
    <inertial>
      <mass value="0"/>
      <origin rpy="0  0  0" xyz="0  0  0"/>
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
    </inertial>
    <collision name="core_003__wall_002_Collision">
      <origin rpy="0  0  0" xyz="0   0  ${wall_height / 2}"/>
      <geometry>
        <box size="${door_space}  ${wall_thickness}  ${wall_height}"/>
      </geometry>
    </collision>
    <visual name="core_003__wall_002_Visual">
      <origin rpy="0  0  0" xyz="0  0  ${wall_height / 2}"/>
      <geometry>
        <box size="${door_space}  ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>
  </link>  
  <gazebo reference="core_003__wall_002">
    <material>PR2/Grey2</material>
    <laserRetro>1000</laserRetro>
    <selfCollide>false</selfCollide>
  </gazebo>
  
  <joint name="core_003__wall_003_joint" type="fixed" >
    <parent link="floor_001_link" />
    <origin xyz="${2 * hall_width + core_width}  ${2 * hall_width + 4.5 * door_space + 2 * door_width}  0" rpy="0  0  1.5708" />
    <child link="core_003__wall_003" />
  </joint>
  <link name="core_003__wall_003">
    <inertial>
      <mass value="0"/>
      <origin rpy="0  0  0" xyz="0  0  0"/>
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
    </inertial>
    <collision name="core_003__wall_003_Collision">
      <origin rpy="0  0  0" xyz="0   0  ${wall_height / 2}"/>
      <geometry>
        <box size="${door_space}  ${wall_thickness}  ${wall_height}"/>
      </geometry>
    </collision>
    <visual name="core_003__wall_003_Visual">
      <origin rpy="0  0  0" xyz="0  0  ${wall_height / 2}"/>
      <geometry>
        <box size="${door_space}  ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>
  </link>  
  <gazebo reference="core_003__wall_003">
    <material>PR2/Grey2</material>
    <laserRetro>1000</laserRetro>
    <selfCollide>false</selfCollide>
  </gazebo>
  
  <joint name="core_003__wall_004_joint" type="fixed" >
    <parent link="floor_001_link" />
    <origin xyz="${2 * hall_width + core_width}  ${2 * hall_width + 6.5 * door_space + 3 * door_width}  0" rpy="0  0  1.5708" />
    <child link="core_003__wall_004" />
  </joint>
  <link name="core_003__wall_004">
    <inertial>
      <mass value="0"/>
      <origin rpy="0  0  0" xyz="0  0  0"/>
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
    </inertial>
    <collision name="core_003__wall_004_Collision">
      <origin rpy="0  0  0" xyz="0   0  ${wall_height / 2}"/>
      <geometry>
        <box size="${3 * door_space}  ${wall_thickness}  ${wall_height}"/>
      </geometry>
    </collision>
    <visual name="core_003__wall_004_Visual">
      <origin rpy="0  0  0" xyz="0  0  ${wall_height / 2}"/>
      <geometry>
        <box size="${3 * door_space}  ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>
  </link>  
  <gazebo reference="core_003__wall_004">
    <material>PR2/Grey2</material>
    <laserRetro>1000</laserRetro>
    <selfCollide>false</selfCollide>
  </gazebo>
    
  <!-- ===================  -->
  <!--     core_004         -->
  
  <joint name="core_004__wall_001_joint" type="fixed" >
    <parent link="floor_001_link" />
    <origin xyz="${2 * hall_width + core_width / 2}  ${2 * hall_width + core_width}  0" rpy="0  0  0" />
    <child link="core_004__wall_001" />
  </joint>
  <link name="core_004__wall_001">
    <inertial>
      <mass value="0"/>
      <origin rpy="0  0  0" xyz="0  0  0"/>
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
    </inertial>
    <collision name="core_004__wall_001_Collision">
      <origin rpy="0  0  0" xyz="0   0  ${wall_height / 2}"/>
      <geometry>
        <box size="${core_width}  ${wall_thickness}  ${wall_height}"/>
      </geometry>
    </collision>
    <visual name="core_004__wall_001_Visual">
      <origin rpy="0  0  0" xyz="0  0  ${wall_height / 2}"/>
      <geometry>
        <box size="${core_width}  ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>
  </link>  
  <gazebo reference="core_004__wall_001">
    <material>PR2/Grey2</material>
    <laserRetro>1000</laserRetro>
    <selfCollide>false</selfCollide>
  </gazebo>

</robot>
