////////////////////////////////
// A move_base director
//
// Written by:  Matthew Peavy
//              Kyungki Kim
// (c) 2021
//

#ifndef UNL_ROBOTICS_MOVE_BASE_DIRECTOR
#define UNL_ROBOTICS_MOVE_BASE_DIRECTOR

//ROS
#include <actionlib/client/simple_action_client.h>
#include <move_base_msgs/MoveBaseAction.h>

// Service messages lead to autogenerated header files in the /devel/include/<projName>
// where <projName> is the name of the project within the CMakeLists.txt file.
// The CMakeLists.txt file must include a directive to generate these message/header files.
#include "unl_smart_robotic_home/node_ready.h"
#include "unl_smart_robotic_home/move_absolute.h"
#include "unl_smart_robotic_home/move_relative.h"


namespace UNL_Robotics {

  typedef actionlib::SimpleActionClient<move_base_msgs::MoveBaseAction> MoveBaseClient;
  
  class move_base_director {
  public:
    move_base_director();
    ~move_base_director();
    
  private:
    bool m_nodeReady;   //Set to true when node is fully ready
    ros::ServiceServer m_service_node_ready;
    ros::ServiceServer m_service_move_absolute;
    ros::ServiceServer m_service_move_relative;
    MoveBaseClient m_actionClient;
    
    bool node_ready(unl_smart_robotic_home::node_ready::Request&  request, 
                    unl_smart_robotic_home::node_ready::Response& response);
    
    bool move_absolute(unl_smart_robotic_home::move_absolute::Request&  request, 
                       unl_smart_robotic_home::move_absolute::Response& response);
    
    bool move_relative(unl_smart_robotic_home::move_relative::Request&  request, 
                       unl_smart_robotic_home::move_relative::Response& response);
    
  };
}

#endif

